repositories:
  - name: prometheus
    url: https://prometheus-community.github.io/helm-charts
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server/

helmDefaults:
  createNamespace: true # default setting - here only to highlight that namespaces are created automatically
  wait: true
  timeout: 300

environments:
  homelab:
    kubeContext: kubernetes-admin@kubernetes
    values:
      - values/values.yaml
---
releases:
  - name: kube-prometheus-stack
    chart: prometheus/kube-prometheus-stack
    version: ~65.3.1
    namespace: monitoring
    values:
      - values/values.yaml
  - name: metrics-server
    chart: metrics-server/metrics-server
    version: ~3.12.2
    namespace: monitoring
    values:
      - values/values-ms.yaml
  - name: monitoring
    chart: monitoring
    version: 0.0.0
    namespace: monitoring
