authentik:
  # -- whether to create the authentik configuration secret
  enabled: false
server:
  envFrom:
    - secretRef:
        name: authentik-secret
  volumes:
    - name: postgres-creds
      secret:
        secretName: postgresql-secret
  volumeMounts:
    - name: postgres-creds
      mountPath: /postgres-creds
      readOnly: true
worker:
  volumes:
    - name: postgres-creds
      secret:
        secretName: postgresql-secret
  volumeMounts:
    - name: postgresql-secret
      mountPath: /postgres-creds
      readOnly: true

postgresql:
  enabled: true
  auth:
  username: authentik
  database: authentik
  existingSecret: postgresql-secret
  secretKeys:
    adminPasswordKey: POSTGRES_PASSWORD
    userPasswordKey: POSTGRES_PASSWORD

redis:
  enabled: true
