authentik:
  # -- whether to create the authentik configuration secret
  enabled: false
server:
  envFrom:
    - secretRef:
        name: authentik
  volumes:
    - name: postgres-creds
      secret:
        secretName: postgresql-secret
  volumeMounts:
    - name: postgres-creds
      mountPath: /postgres-creds
      readOnly: true
worker:
  volumes:
    - name: postgres-creds
      secret:
        secretName: postgresql-secret
  volumeMounts:
    - name: postgresql-secret
      mountPath: /postgres-creds
      readOnly: true

postgresql:
  enabled: true
  auth:
    username: authentik
    database: authentik

redis:
  enabled: true
