repositories:
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts
    skipTLSVerify: true

helmDefaults:
  createNamespace: true # default setting - here only to highlight that namespaces are created automatically
  insecureSkipTLSVerify: true
  wait: true
  timeout: 300

environments:
  homelab:
    kubeContext: kubernetes-admin@kubernetes
    values:
      - values/values.yaml
---
releases:
  - name: istio-base
    chart: istio/base
    version: ~1.24.2
    labels:
      release: istio-base
    namespace: istio-system
    insecureSkipTLSVerify: true
    missingFileHandler: Error
    values:
      - values-templates/base.yaml.gotmpl
  - name: istiod
    chart: istio/istiod
    version: ~1.24.2
    labels:
      release: istiod
    namespace: istio-system
    insecureSkipTLSVerify: true
    missingFileHandler: Error
    values:
      - values-templates/istiod.yaml.gotmpl

  - name: istio-cni
    chart: istio/cni
    version: ~1.24.2
    labels:
      release: istio-cni
    namespace: istio-system
    insecureSkipTLSVerify: true
    # TODO: Needed to enable ambient mode
    # set:
    # - name: profile
    #   value: "ambient"

  # TODO: Needed to enable ambient mode
  # - name: istio-ztunnel
  #   chart: istio/ztunnel
  #   version: ~1.24.0
  #   labels:
  #     release: istio-ztunnel
  #   insecureSkipTLSVerify: true
  #   namespace: istio-system
  - name: istio-gateway
    labels:
      release: istio-gateway
    chart: gateway
    values:
      - values-templates/istio-gateway.yaml.gotmpl
    version: ~1.24.2
    insecureSkipTLSVerify: true
    namespace: istio-gateway
