---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-secret
  namespace: authentik
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBjQ3PpuW75XgZ0I5ja9S2sW5U83wGget/eVpps5z9SHjs3rkqcq2NDUZKPzg4eM6UjRP/xCiftlriv7YtU3uZL+YBDb2Y10oGAdOPZ4htseKq92aJCZGBVz/RPMA/kzIYZRpQixpvhi8CVMUTz5WGM5YUlORiUjcMVggmhLgvg1ci6b+ztgpt/ByqOKbCNf7vlKTOH3VmmTo1MpHnz3aW4wEIoy9lE6PF3WOSr92DaiKCurVk6Gjh+fDTfM1taf6uETbUkAadJbm4D8c+d00eaQgil5Bv66n6tL+0KZsUqfAkfkuKL2psur5vPKifzpBHXx2AwrkSJsCm6HG4HKkO3IyJ61EYaPHmSESMKVJPT24RSvo0veSms6alWP0tY4b/k4H6yJrq6HJBzALZ+4+2pha7mz4SCqIU7EymVCuyRNVz88j41fHQIKvVrMv+fdduKtVvcxEDWvSCY2+nUjlBwwU+JTdZmHZJOjt0ile4+3PyIYkr+Xjd6D6ATJJXGWBtpQQeazlsBpeCpNWGOjBUQQ+ciRd8e8FfFFNShQyyJjlkUP1XFfhfvBnOtwxhgAPI1hmDyVV5IwGVP+4lZSAN3WN5Fh8baeMu4XMPXeIMJYYsxa/2sSmwSWx936cKkuUFCtbtru23bB44AiEwME+LLkFWAN6CXzHrMcVatUp46SOmgqtRe97gjG2cWIJxz0BsnyxQhSS6ojHcBk4ULzq5Bs4fhaE/iLY9tQl2ib880/bADuJIkgk0EgnxEJVDg
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-secret
      namespace: authentik
