apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: prod-cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: prod-cluster-issuer
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
            - kind: Gateway
              name: istio-gateway
              namespace: istio-gateway
