apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: prod-cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: prod-cluster-issuer
    solvers:
    - dns01:
        cloudflare:
          email: zadrozny.tomasz@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
