apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server
  namespace: argocd
spec:
  secretName: argocd-server
  issuerRef:
    name: letsencrypt-prod # name of the ClusterIssuer
    kind: ClusterIssuer
  dnsNames:
    - argocd.tomekz.dev
