apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
namespace: monitoring
metadata:
  name: istio-sidecars
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      security.istio.io/tlsMode: 'istio'
  podMetricsEndpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
  namespaceSelector:
    any: true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
namespace: monitoring
metadata:
  name: istio-ingressgateway
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  namespaceSelector:
    matchNames:
      - istio-gateway
  endpoints:
    - targetPort: http-envoy-prom
      path: /stats/prometheus
